# Site settings
author: Michael Evans
title: The Mevans Blog
header-img: img/home-bg.png
email: michael@michaelgregoryevans.com
copyright_name: Michael Evans
description: > # this means to ignore newlines until "baseurl:"
  Here's where I write about things
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mevanstron

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
